version: "2"
run:
  modules-download-mode: readonly
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_test.go
      - api
      - third_party$
      - builtin$
      - examples$
  settings:
    govet:
      disable:
        - inline
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
