language: go
dist: bionic

go:
  - 1.13.x
  # - master

# TODO: caching docker image https://stackoverflow.com/questions/32866599/can-travis-ci-cache-docker-images
env:
  global:
    - GO111MODULE=on

install: skip

cache:
  directories:
    - $GOPATH/pkg/mod

jobs:
  allow_failures:
    - env:
        - ALLOW_FAIL=true
  include:
    - stage: test
      name: "Unit Tests"
      script:
        - docker-compose up -d
        - go test -tags tests ./... -v -cover
    - stage: test
      name: "Go Lint"
      script:
        - go get -u golang.org/x/lint/golint
        - find . -type f -name "*\.go" | grep -v "zz_generated" | grep -v "proxy/proxysql.go" | while read line; do
            golint -set_exit_status $line || exit 1;
          done
    - stage: test
      name: "Go Vet"
      script:
        - go vet ./...
    - stage: integration
      name: "Integration test"
      services:
        - snap
        - docker
        - jq
      script:
        - sudo snap install kubectl --classic && sudo snap install helm --classic
        - make k3d_setup && sh integration/test.sh