version: "3.3"
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test1234"
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test1234"
  sqladmin:
    image: ghcr.io/kloeckner-i/cloudish-sql:v1.0.0
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: "DEBUG"
    command:
      - --db-address=postgres:5432
