serviceMonitorName: ""

dbinstances: {}

nodeSelector: {}

exporter:
  postgres:
    image: wrouesnel/postgres_exporter:latest
    query: |
      pg_postmaster:
        query: "SELECT pg_postmaster_start_time as start_time_seconds from pg_postmaster_start_time()"
        metrics:
          - start_time_seconds:
              usage: "GAUGE"
              description: "Time at which postmaster started"

      pg_stat_user_tables:
        query: "SELECT schemaname, relname, seq_scan, seq_tup_read, idx_scan, idx_tup_fetch, n_tup_ins, n_tup_upd, n_tup_del, n_tup_hot_upd, n_live_tup, n_dead_tup, n_mod_since_analyze, last_vacuum, last_autovacuum, last_analyze, last_autoanalyze, vacuum_count, autovacuum_count, analyze_count, autoanalyze_count FROM pg_stat_user_tables"
        metrics:
          - schemaname:
              usage: "LABEL"
              description: "Name of the schema that this table is in"
          - relname:
              usage: "LABEL"
              description: "Name of this table"
          - seq_scan:
              usage: "COUNTER"
              description: "Number of sequential scans initiated on this table"
          - seq_tup_read:
              usage: "COUNTER"
              description: "Number of live rows fetched by sequential scans"
          - idx_scan:
              usage: "COUNTER"
              description: "Number of index scans initiated on this table"
          - idx_tup_fetch:
              usage: "COUNTER"
              description: "Number of live rows fetched by index scans"
          - n_tup_ins:
              usage: "COUNTER"
              description: "Number of rows inserted"
          - n_tup_upd:
              usage: "COUNTER"
              description: "Number of rows updated"
          - n_tup_del:
              usage: "COUNTER"
              description: "Number of rows deleted"
          - n_tup_hot_upd:
              usage: "COUNTER"
              description: "Number of rows HOT updated (i.e., with no separate index update required)"
          - n_live_tup:
              usage: "GAUGE"
              description: "Estimated number of live rows"
          - n_dead_tup:
              usage: "GAUGE"
              description: "Estimated number of dead rows"
          - n_mod_since_analyze:
              usage: "GAUGE"
              description: "Estimated number of rows changed since last analyze"
          - last_vacuum:
              usage: "GAUGE"
              description: "Last time at which this table was manually vacuumed (not counting VACUUM FULL)"
          - last_autovacuum:
              usage: "GAUGE"
              description: "Last time at which this table was vacuumed by the autovacuum daemon"
          - last_analyze:
              usage: "GAUGE"
              description: "Last time at which this table was manually analyzed"
          - last_autoanalyze:
              usage: "GAUGE"
              description: "Last time at which this table was analyzed by the autovacuum daemon"
          - vacuum_count:
              usage: "COUNTER"
              description: "Number of times this table has been manually vacuumed (not counting VACUUM FULL)"
          - autovacuum_count:
              usage: "COUNTER"
              description: "Number of times this table has been vacuumed by the autovacuum daemon"
          - analyze_count:
              usage: "COUNTER"
              description: "Number of times this table has been manually analyzed"
          - autoanalyze_count:
              usage: "COUNTER"
              description: "Number of times this table has been analyzed by the autovacuum daemon"

      pg_database:
        query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size FROM pg_database"
        metrics:
          - datname:
              usage: "LABEL"
              description: "Name of the database"
          - size:
              usage: "GAUGE"
              description: "Disk space used by the database"

      pg_stat_database:
        query: "SELECT datname, numbackends, xact_commit, xact_rollback, blks_read, blks_hit, tup_fetched, tup_inserted, tup_updated, tup_deleted, temp_bytes, deadlocks FROM pg_catalog.pg_stat_database;"
        metrics:
          - datname:
              usage: "LABEL"
              description: "database NAME"
          - numbackends:
              usage: "COUNTER"
              description: "Number of backends currently connected to this database."
          - xact_commit:
              usage: "COUNTER"
              description: "Number of transactions in this database that have been committed"
          - xact_rollback:
              usage: "COUNTER"
              description: "Number of transactions in this database that have been rolled back"
          - blks_read:
              usage: "GAUGE"
              description: "Number of disk blocks read in this database"
          - blks_hit:
              usage: "GAUGE"
              description: "Number of times disk blocks were found already in the buffer cache, so that a read was not necessary"
          - tup_fetched:
              usage: "COUNTER"
              description: "Number of rows fetched by queries in this database"
          - tup_inserted:
              usage: "COUNTER"
              description: "Number of rows inserted by queries in this database"
          - tup_updated:
              usage: "COUNTER"
              description: "Number of rows updated by queries in this database"
          - tup_deleted:
              usage: "COUNTER"
              description: "Number of rows deleted by queries in this database"
          - temp_bytes:
              usage: "GAUGE"
              description: "Total amount of data written to temporary files by queries in this database."
          - deadlocks:
              usage: "COUNTER"
              description: "Number of deadlocks detected in this database"

      pg_stat_statements:
        query: "SELECT userid, pgss.dbid, pgdb.datname, queryid, query, calls, total_time, mean_time, rows FROM pg_stat_statements pgss LEFT JOIN (select oid as dbid, datname from pg_database) as pgdb on pgdb.dbid = pgss.dbid WHERE not queryid isnull ORDER BY mean_time desc limit 20"
        metrics:
          - userid:
              usage: "LABEL"
              description: "User ID"
          - dbid:
              usage: "LABEL"
              description: "database ID"
          - datname:
              usage: "LABEL"
              description: "database NAME"
          - queryid:
              usage: "LABEL"
              description: "Query unique Hash Code"
          - query:
              usage: "LABEL"
              description: "Query class"
          - calls:
              usage: "COUNTER"
              description: "Number of times executed"
          - total_time:
              usage: "COUNTER"
              description: "Total time spent in the statement, in milliseconds"
          - mean_time:
              usage: "GAUGE"
              description: "Mean time spent in the statement, in milliseconds"
          - rows:
              usage: "COUNTER"
              description: "Total number of rows retrieved or affected by the statement"

mysql:
  enabled: false

postgresql:
  enabled: false

serviceMonitor:
  enabled: false

# Overwrite Namespace if secrets get created and release namespace != operator ns
# operatorNamespace:
