image:
  repository: registry.kci.rocks/devops/db-operator
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
   cpu: "0.5"
   memory: 512Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector:
  env: production

annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "60000"
