---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kinda.rocks
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kinda.rocks
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - kinda.rocks
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kinda.rocks
  resources:
  - dbinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kinda.rocks
  resources:
  - dbinstances/finalizers
  verbs:
  - update
- apiGroups:
  - kinda.rocks
  resources:
  - dbinstances/status
  verbs:
  - get
  - patch
  - update
