apiVersion: kci.rocks/v1alpha1
kind: DbInstance
metadata:
  name: pg-generic-instance
spec:
  adminSecretRef:
    Namespace: {{ .Release.Namespace }}
    Name: pg-generic-admin-secret
  engine: postgres
  generic:
    host: {{ .Values.postgres.serviceName }}.{{ .Release.Namespace }}
    port: 5432
    backupHost: {{ .Values.postgres.serviceName }}.{{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-generic-admin-secret
type: Opaque
data:
  password: {{ .Values.postgres.adminPassword | b64enc }}
  user: {{ .Values.postgres.adminUser | b64enc }}