---
apiVersion: "kci.rocks/v1alpha1"
kind: "Database"
metadata:
  name: "example-db"
  labels:
    env: test
spec:
  secretName: example-db-credentials # where to save db name user, password for application
  instance: k8stest-review
  deletionProtected: false
  backup:
    enable: true
    cron: "0 0 * * *"