apiVersion: kci.rocks/v1alpha1
kind: DbInstance
metadata:
  name: "example-generic"
spec:
  adminSecretRef:
    Name: example-instance-admin-secret
    Namespace: << namespace of admin secret >>
  engine: postgres
  generic:
    host: << remote database server address >>
    port: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: example-instance-admin-secret
  namespace: << operator namespace >>
type: Opaque
data:
  user: cG9zdGdyZXM=
  password: c2VjdXJlcGFzc3dvcmQK