apiVersion: "kci.rocks/v1alpha1"
kind: "Database"
metadata:
  name: "pg-db-test"
  labels:
    env: test
spec:
  secretName: pg-db-test-credentials # where to save db name user, password for application
  instance: pg-local-test
  backup:
    enable: false
    cron: ""
  deletionProtected: false