---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "db-operator.name" . }}
  labels:
    {{- include "db-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "db-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "db-operator.labels" . | nindent 8 }}
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | trim | indent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "db-operator.name" . }}-sa
      {{- end }}

     {{- if .Values.security }}
      securityContext:
        runAsUser: {{ .Values.security.runAsUser }}
        fsGroup: {{ .Values.security.fsGroup }}
     {{- end }}

      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ template "db-operator.github_packages_image_version" . }}"
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - db-operator
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.image.logLevel }}
            - name: OPERATOR_NAME
              value: "db-operator"
            - name: WATCH_NAMESPACE
              value: {{ .Values.watchNamespace | quote }}
            - name: RECONCILE_INTERVAL
              value: {{ .Values.reconcileInterval | quote }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            {{- if .Values.secrets.gsql }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/run/secrets/gcloudsqladmin/credentials.json"
            - name: GCSQL_CLIENT_CREDENTIALS
              value: "/run/secrets/gcloudsqlclient/credentials.json"
            {{- end }}
            - name: CONFIG_PATH
              value: "/run/config/config.yaml"
          volumeMounts:
          {{- if .Values.secrets.gsql }}
          - mountPath: /run/secrets/gcloudsqladmin
            name: serviceaccount-cloudsql-admin
            readOnly: true
          - mountPath: /run/secrets/gcloudsqlclient
            name: serviceaccount-cloudsql-client
            readOnly: true
          {{- end }}
          - mountPath: /run/config/
            name: config-volume
            readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.affinity  | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
    {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
    {{- end }}
      volumes:
      {{- if .Values.secrets.gsql }}
        - name: serviceaccount-cloudsql-admin
          secret:
            defaultMode: 420
            secretName: cloudsql-admin-serviceaccount
        - name: serviceaccount-cloudsql-client
          secret:
            defaultMode: 420
            secretName: cloudsql-readonly-serviceaccount
      {{- end }}
        - name: config-volume
          configMap: 
            name: {{ template "db-operator.name" . }}-config
