{{- if .Values.rbac.create -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "db-operator.name" . }}
  labels:
    app: {{ template "db-operator.name" . }}
    chart: {{ template "db-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - kci.rocks
  resources:
  - "*"
  verbs:
  - watch
  - update
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - secrets
  - services
  - events
  verbs:
  - create
  - update
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  - events
  verbs:
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - update
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  resourceNames:
  - servicemonitors.monitoring.coreos.com
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - update
  - patch
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - create
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - create
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "db-operator.name" . }}-sa
  labels:
    {{- include "db-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "db-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "db-operator.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}