---
apiVersion: "kci.rocks/v1alpha1"
kind: "Database"
metadata:
  name: "example-db"
  labels:
    env: test
spec:
  secretName: example-db-credentials # where to save db name user, password for application
  instance: generic-postgres
  deletionProtected: false
  backup:
    enable: true
    cron: "0 0 * * *"
  # connectionStringTemplate: |
    # "conn_string::jdbc:{{ .Protocol }}://{{ .UserName }}:{{ .Password }}@{{ .DatabaseHost }}:{{ .DatabasePort }}/{{ .DatabaseName }}"
  # secretsTemplates:
    # CONNECTION_STRING_3: "{{ .Password }}{{ .Password }}{{ .Password }}@{{ .DatabaseHost }}:{{ .DatabasePort }}/{{ .DatabaseName }}"
    # CONNECTION_STRING_2: "jdbc:{{ .Protocol }}://{{ .UserName }}:{{ .Password }}@{{ .DatabaseHost }}:{{ .DatabasePort }}/{{ .DatabaseName }}"
