repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: kloeckneri
    url: https://kloeckner-i.github.io/charts/

releases:
  - name: kci-db-operator
    chart: kloeckneri/db-operator
    version: 1.3.0
    namespace: db-operator
    installed: true
    labels:
      install-first: "true"
    values:
      - image:
          repository: my-db-operator
          tag: 1.0.0-dev
          pullPolicy: Never
      - resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      - annotations: {}
      - config: {}

  - name: kci-db-instance
    installed: true
    namespace: db-operator
    chart: kloeckneri/db-instances
    version: 1.3.4
    values:
      - dbinstances:
          generic-postgres:
            monitoring:
              enabled: false
            adminSecretRef:
              Name: example-generic-admin-secret
              Namespace: db-operator
            engine: postgres
            generic:
              host: postgres-instance-postgresql
              port: 5432
            secrets:
              adminUser: postgres
              adminPassword: 0hFk8zgUMR

  - name: postgres-instance
    installed: true
    namespace: db-operator
    chart: bitnami/postgresql
    version: 11.1.26
    values:
      - global.postgresql.auth.postgresPassword: 0hFk8zgUMR
