{{- if .Values.rbac.create -}}
{{ template "db-operator.rbac_role" . }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "db-operator.name" . }}-sa
  labels:
    {{- include "db-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "db-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "db-operator.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}