{{- if .Values.rbac.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "db-operator.name" . }}
  labels:
    app: {{ template "db-operator.name" . }}
    chart: {{ template "db-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - kci.rocks
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - secrets
  - databases
  - services
  - events
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "db-operator.name" . }}-sa
  labels:
    app: {{ template "db-operator.name" . }}
    chart: {{ template "db-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "db-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}  
roleRef:
  kind: ClusterRole
  name: {{ template "db-operator.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}