{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "db-operator.serviceAccountName" . }}
  labels:
    {{- include "db-operator.labels" . | nindent 4 }}
{{- end -}}