{{- $release := .Release }}
{{- $heritage := .Release.Service }}
{{- $chart := .Chart.Name }}
{{- $operatorNs := include "db-instances.name" . -}}
{{- if .Values.dbinstances }}
{{- range $name, $value := .Values.dbinstances }}
---
apiVersion: "kci.rocks/v1alpha1"
kind: "DbInstance"
metadata:
  name: {{ $name }}
  annotations:
    {{- if $value.google }}
    checksum/config: {{ $value.google.configMap.data | sha256sum }}
    {{- end }}
  labels:
    chart: {{ $chart }}
    release: {{ $release.Name }}
    heritage: {{ $heritage }}
spec:
  engine: {{ $value.engine }}
  {{- if $value.existingAdminSecret }}
  adminSecretRef: 
    Namespace: {{ $value.existingAdminSecret.namespace }}
    Name: {{ $value.existingAdminSecret.name }}
  {{- else }}
  adminSecretRef: 
    Namespace: {{ $operatorNs }}
    Name: {{ $name }}-admin-secret
  {{- end }}
  {{- if $value.backup }}
  backup:
{{ toYaml $value.backup | indent 4 }}
  monitoring:
    enabled: {{ $value.monitoring.enabled }}
  {{- end }}
  {{- if $value.google }}
  google:
    instance: {{ $value.google.instanceName }}
    configmapRef: 
      Namespace: {{ $operatorNs }}
      Name: {{ $value.google.configMap.name }}
  {{- end }}
  {{- if $value.generic }}
  generic:
    host: {{ $value.generic.host }}
    port: {{ $value.generic.port }}
  {{- if $value.generic.publicIp }}
    publicIp: {{ $value.generic.publicIp }}
  {{- end }}
  {{- if $value.generic.backupHost }}
    backupHost: {{ $value.generic.backupHost }}
  {{- end }}
  {{- end }}
  {{- if $value.percona }}
  percona:
    servers:
    {{- range $server := $value.percona.servers }}
    - host: {{ $server.host }}
      port: {{ $server.port }}
      maxConn: {{ $server.maxConn }}
      {{- if $server.readonly }}
      readonly: {{ $server.readonly }}
      {{- end }}
    {{- end }}
    monitorUserSecretRef:
      Name: {{ $name }}-monitoruser-secret
      Namespace: {{ $operatorNs }}
  {{- end }}
{{- if not $value.existingAdminSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-admin-secret
  namespace: {{ $operatorNs }}
  labels:
    chart: {{ $chart }}
    release: {{ $release.Name }}
    heritage: {{ $heritage }}
type: Opaque
data:
  user: {{ $value.secrets.adminUser | b64enc }}
  password: {{ $value.secrets.adminPassword | b64enc }}
{{- end }}
---
{{- if $value.google }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $value.google.configMap.name }}
  namespace: {{ $operatorNs }}
  labels:
    chart: {{ $chart }}
    release: {{ $release.Name }}
    heritage: {{ $heritage }}
data:
  config: |
{{ $value.google.configMap.data | indent 4 }}
{{- end }}
{{- if $value.percona }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-monitoruser-secret
  namespace: {{ $operatorNs }}
  labels:
    chart: {{ $chart }}
    release: {{ $release.Name }}
    heritage: {{ $heritage }}
type: Opaque
data:
  user: {{ $value.percona.monitoruser.name | b64enc }}
  password: {{ $value.percona.monitoruser.password | b64enc }}
{{- end }}
{{- end }}
{{- end }}