---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-google-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googleAPI
      role: test
  template:
    metadata:
      labels:
        app: googleAPI
        role: test
    spec:
      containers:
        - name: api
          image: ghcr.io/kloeckner-i/cloudish-sql:v1.0.0
          ports:
          - containerPort: 8080
            name: http
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "DEBUG"
          command:
            - /usr/local/bin/cloudish-sql
            - --db-address=pg-test-db:5432
---
apiVersion: v1
kind: Service
metadata:
  name: mock-google-api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: googleAPI
    role: test
  type: ClusterIP
