{
 "title": "K8s - db-operator",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_time_seconds{cluster=~\".+k8s\"}, cluster)"
    }
   },
   {
    "name": "dbinstance",
    "query": {
     "query": "label_values(db_operator_dbinstance_phase{cluster=~\"$cluster\"}, dbinstance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "$cluster - DB Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(db_operator_database_status{cluster=~\"$cluster\", dbinstance=~\"$dbinstance\"})"
    }
   ]
  },
  {
   "title": "DB Instance - Phase Runtime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(db_operator_handler_dbinstance_seconds_sum{cluster=~\"$cluster\"}[2m])",
     "legendFormat": "{{cluster}}-{{ phase }}"
    }
   ]
  },
  {
   "title": "Databases - Phase Runtime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(db_operator_handler_database_seconds_sum{cluster=~\"$cluster\"}[2m])",
     "legendFormat": "Time {{cluster}}-{{ phase }}"
    },
    {
     "expr": "count(delta(db_operator_handler_database_phase_error{cluster=~\"$cluster\"}[5m])>0) by (cluster)",
     "legendFormat": "Errors {{cluster}}"
    }
   ]
  },
  {
   "title": "DB Instance - Phase",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(db_operator_dbinstance_phase{cluster=~\"$cluster\",dbinstance=~\"$dbinstance\"}) by (cluster,dbinstance)"
    }
   ]
  },
  {
   "title": "Databases - Phase",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(db_operator_database_phase{cluster=~\"$cluster\",dbinstance=~\"$dbinstance\"}) by (cluster,dbinstance,db_namespace,database)"
    }
   ]
  },
  {
   "title": "Databases status not healthy",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "avg(db_operator_database_status{cluster=~\"$cluster\",dbinstance=~\"$dbinstance\"}) by (cluster, dbinstance, database) < 1"
    }
   ]
  }
 ]
}