apiVersion: kci.rocks/v1alpha1
kind: DbInstance
metadata:
  name: {{ .Values.instance.name }}
spec:
  adminSecretRef:
    Namespace: {{ .Release.Namespace }}
    Name: {{ .Values.instance.name }}-admin-password
  engine: mysql
  generic:
    host: {{ .Values.mysql.serviceName }}.{{ .Release.Namespace }}
    port: 3306
    publicIp: "1.2.3.4"
    backupHost: {{ .Values.mysql.serviceName }}.{{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.instance.name }}-admin-password
type: Opaque
data:
  password: {{ .Values.mysql.adminPassword | b64enc }}
  user: {{ .Values.mysql.adminUser | b64enc }}