name: Release Charts

on:
  push:
    branches:
      - "**"
  # workflow_run:
  # workflows: ["Build and Test"]
  # branches: [master, METAL-3280-add-a-job-for-checking-chart-with-different-values]
  # types:
  # - completed

jobs:
  chart-release:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0

      - name: Run chart-testing (lint)
        run: ct lint --validate-maintainers=false --check-version-increment

      # - name: Run chart-releaser
      # uses: helm/chart-releaser-action@v1.2.1
      # env:
      # CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
