name: Helm lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths: 
      - "charts/**"
jobs:
  helm-lint: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0

      - name: Run chart-testing (lint)
        run: ct lint --validate-maintainers=false
