name: Publish Docker image

on:
  release:
    types: [published, edited]

env:
  manufacturer: db-operator
  product_name: db-operator
  go_version: "1.22.2"
  go_os: linux
  main_go_path: ./cmd/main.go

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - go_arch: "amd64"
            docker_arch: "amd64"
          - go_arch: "arm64"
            docker_arch: "arm64/v8"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set the image metadata
        run: ./build/set_image_metadata

      - name: Build an image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: db-operator-devel
          tags: ${{ env.TAGS }}
          platforms: linux/amd64, linux/arm64/v8
          containerfiles: |
            ./Containerfile
          labels: ${{ env.ANNOTATIONS }}

      - name: Push the image to GHCR
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
