---
# -- Quick checks mostly related to the code-related worklow
name: Repo checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  repo-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
      - uses: actions/setup-go@v7
      - uses: pre-commit/action@v3.0.1
      - uses: go-task/setup-task@v2
      - name: Check code generation
        run: |-
          task kubebuilder:manifest && task kubebuilder:generate
          if [[ -n $(git status --porcelain) ]]; then
            echo "Please update generated code using 'task manifest and task generate' and push the changes"
            exit 1
          fi
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v2.1.0
