name: Test the image build on Pull Request

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: docker/setup-qemu-action@v4
      - uses: go-task/setup-task@v2
      - run: task container:set-image-metadata
      - name: Set the operator version from the tag
        run: |-
          echo OPERATOR_VERSION=${{ github.sha }} >> "$GITHUB_ENV"
      - name: Build an image
        id: build-image
        uses: redhat-actions/buildah-build@v3
        with:
          image: db-operator-dev
          tags: ${{ env.TAGS }}
          platforms: linux/amd64, linux/arm64/v8
          build-args: |
            OPERATOR_VERSION=${{ env.OPERATOR_VERSION }}
          containerfiles: |
            ./Containerfile
          labels: ${{ env.ANNOTATIONS }}
      - name: Export image for scanning locally
        id: export-image
        run: |
          buildah push ${{ steps.build-image.outputs.image }}:${{ env.TAGS }} \
            docker-archive:/tmp/scan-image.tar
      - name: Run Trivy vulnerability scanner
        id: trivy-scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "image"
          input: /tmp/scan-image.tar
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
        env:
          TRIVY_DISABLE_VEX_NOTICE: "false"
